### PR TITLE
Multiple possible bean candidates found

### LINKED ISSUE #547: Multiple possible bean candidates found
### Expected Behavior

From the documentation:

>There’s two ways you can provide error handling.
>
>Locally: your [@PubSubListener](https://micronaut-projects.github.io/micronaut-gcp/latest/api/io/micronaut/gcp/pubsub/annotation/PubSubListener.html) class implements [PubSubMessageReceiverExceptionHandler](https://micronaut-projects.github.io/micronaut-gcp/latest/api/io/micronaut/gcp/pubsub/exception/PubSubMessageReceiverExceptionHandler.html), then any error related to Subscriptions of that class will be handled by your class.
>
>Globally: You define a new implementation of [PubSubMessageReceiverExceptionHandler](https://micronaut-projects.github.io/micronaut-gcp/latest/api/io/micronaut/gcp/pubsub/exception/PubSubMessageReceiverExceptionHandler.html) which [replaces](https://docs.micronaut.io/latest/guide/#replaces) [DefaultPubSubMessageReceiverExceptionHandler](https://micronaut-projects.github.io/micronaut-gcp/latest/api/io/micronaut/gcp/pubsub/exception/DefaultPubSubMessageReceiverExceptionHandler.html).

The expectation is that you can implement `PubSubMessageReceiverExceptionHandler` on each subscription to handle errors for just that subscription but when you try and do that you get a `DependencyInjectionException` since the `PubSubConsumerAdvice` doesn't specify what it is trying to inject and the "local" and "global" variants use the same interface.

Note that this behavior actually worked in 2.5.13 so it seems related to one of the 3.X breaking changes around unqualified injection.

### Actual Behaviour

The microservice fails to start with the following error:
```DependencyInjectionException: Failed to inject value for parameter [exceptionHandler] of class: io.micronaut.gcp.pubsub.intercept.PubSubConsumerAdvice```

### Steps To Reproduce

Have multiple `@PubSubListener` beans that implement `PubSubMessageReceiverExceptionHandler` like the documentation implies.

### Environment Information

```
------------------------------------------------------------
Gradle 7.3.3
------------------------------------------------------------

Build time:   2021-12-22 12:37:54 UTC
Revision:     6f556c80f945dc54b50e0be633da6c62dbe8dc71

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.13 (Eclipse Adoptium 11.0.13+8)
OS:           Mac OS X 11.6.2 x86_64
```

### Example Application

_No response_

### Version

`micronaut bom v3.3.1` & `micronaut-gcp-pubsub v4.0.0`

### PR DESCRIPTION
**Pull request by guillermocalvo**
Fixes #547

### CODE REVIEW

File: gcp-pubsub/src/main/java/io/micronaut/gcp/pubsub/exception/DefaultPubSubMessageReceiverExceptionHandler.java [hunk 1]
```diff
@@ -30,6 +31,7 @@
  * @since 2.0.0
  */
 @Singleton
+@Primary
```
Comment (sdelamo) [inline gcp-pubsub/src/main/java/io/micronaut/gcp/pubsub/exception/DefaultPubSubMessageReceiverExceptionHandler.java:34]: I don't think this is correct. It is smelly we have to force our bean to be `@Primary`

Comment (guillermocalvo) [reply gcp-pubsub/src/main/java/io/micronaut/gcp/pubsub/exception/DefaultPubSubMessageReceiverExceptionHandler.java:34]: @sdelamo 

> I don't think this is correct. It is smelly we have to force our bean to be `@Primary`

I annotated it as `@Primary` because that's the way the [default Kafka exception handler](https://github.com/micronaut-projects/micronaut-kafka/blob/master/kafka/src/main/java/io/micronaut/configuration/kafka/exceptions/DefaultKafkaListenerExceptionHandler.java#L40) was implemented in the Kafka module.

> Have you tried annotating it with `@Secondary`?

Yes I have; it doesn't work when it's annotated as `@Secondary`.

**Comment by sdelamo** [comment]
ping @dstepanov

File: gcp-pubsub/src/main/java/io/micronaut/gcp/pubsub/exception/DefaultPubSubMessageReceiverExceptionHandler.java (hunk 1 above)
Comment (sdelamo) [reply gcp-pubsub/src/main/java/io/micronaut/gcp/pubsub/exception/DefaultPubSubMessageReceiverExceptionHandler.java:34]: This still looks smelly to me, but it seems we created the API with the @Primary in mind. The test which shows how to override the default handler also uses @Primary https://github.com/micronaut-projects/micronaut-gcp/blob/master/gcp-pubsub/src/test/groovy/io/micronaut/gcp/pubsub/bind/ExceptionHandlerSpec.groovy#L104

I am going to merge this and hopefully we can have a better design in the future.

**Review by sdelamo — APPROVED** [review]

File: gcp-pubsub/src/main/java/io/micronaut/gcp/pubsub/exception/DefaultPubSubMessageReceiverExceptionHandler.java (hunk 1 above)
Comment (dstepanov) [reply gcp-pubsub/src/main/java/io/micronaut/gcp/pubsub/exception/DefaultPubSubMessageReceiverExceptionHandler.java:34]: The design is a bit messy, but I guess the primary is OK here
